services:
  fetcher:
    build: .
    container_name: docker-headless-fetcher
    ports:
      - "${HTTP_PORT-8080}:8080"
    environment:
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: unless-stopped
